<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function edville_tourist_tax_commerce_tax_type_calculate_rates($tax_type, $line_item) {
    if ($line_item->type == "rooms_booking") {
        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
        dsm($line_item_wrapper);
    }
}