<?php
/**
 * @file
 * feature_about_area_nodes.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function feature_about_area_nodes_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Sustainability',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'e8c75f8b-9df3-4398-b002-dfa33a557b6f',
  'type' => 'about',
  'language' => 'und',
  'created' => 1421730918,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0d82bab5-c1ee-4969-a628-181e66efc5a0',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>You can learn more by viewing our annual Sustainability Report, but here are a few of the environmentally friendly steps we have taken so far:</p>

<ul>
	<li>ENERGY STAR Certified</li>
	<li>Diverting 68% of our overall waste stream from landfills</li>
	<li>Composting an average of 14-17 tons per month</li>
	<li>Retrofits have reduced water use by 15% and energy use by 32%</li>
	<li>Employee transit subsidies have saved 9,500 gallons of gas each year</li>
	<li>Enacting an aggressive property-wide recycling program</li>
	<li>Reducing our carbon footprint through a biodiesel shuttle and guest offset program</li>
	<li>Offsetting 25% of our annual electricity use by purchasing 900,000 kWh of renewable power</li>
	<li>Purchasing 65% of our food products seasonally within a 500-mile region</li>
</ul>

<p>As part of ongoing efforts to make Portland a healthier place to live, work, and conduct business, DoubleTree by Hilton Portland seeks first to purchase equipment, products and materials that are recyclable, made of recycled content and reduce waste. Per our Purchasing Pledge, we will work to mitigate fuel waste and create demand for environmentally friendly products by purchasing local products from like-minded vendors.</p>

<p>We invite you to take a close look at our eco-friendly initiatives, green meetings, and look forward to welcoming you to our hotel.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>You can learn more by viewing our annual Sustainability Report, but here are a few of the environmentally friendly steps we have taken so far:</p>
<ul><li>ENERGY STAR Certified</li>
<li>Diverting 68% of our overall waste stream from landfills</li>
<li>Composting an average of 14-17 tons per month</li>
<li>Retrofits have reduced water use by 15% and energy use by 32%</li>
<li>Employee transit subsidies have saved 9,500 gallons of gas each year</li>
<li>Enacting an aggressive property-wide recycling program</li>
<li>Reducing our carbon footprint through a biodiesel shuttle and guest offset program</li>
<li>Offsetting 25% of our annual electricity use by purchasing 900,000 kWh of renewable power</li>
<li>Purchasing 65% of our food products seasonally within a 500-mile region</li>
</ul><p>As part of ongoing efforts to make Portland a healthier place to live, work, and conduct business, DoubleTree by Hilton Portland seeks first to purchase equipment, products and materials that are recyclable, made of recycled content and reduce waste. Per our Purchasing Pledge, we will work to mitigate fuel waste and create demand for environmentally friendly products by purchasing local products from like-minded vendors.</p>
<p>We invite you to take a close look at our eco-friendly initiatives, green meetings, and look forward to welcoming you to our hotel.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-64945.jpg',
        'uri' => 'public://wallhaven-64945.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 754826,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'ff137f34-7b28-43b2-b59a-2ae754256cb6',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1200,
        'uuid_features_file_url' => 'public://wallhaven-64945.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>As a sustainable hotel, we pledge to:</p>

<ul>
	<li>Lead by example, sharing our successes and failures with the&nbsp;community and our industry partners</li>
	<li>Hold every decision to the standard of our triple bottom line: benefitting the community, providing the best workplace for our employees, and enhancing our guest experience</li>
	<li>Grow our business responsibly, by tracking the progress of our efforts and by continuously seeking areas for improvement</li>
	<li>And, above all, to maintain transparency in all these efforts</li>
</ul>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>As a sustainable hotel, we pledge to:</p>
<ul><li>Lead by example, sharing our successes and failures with the community and our industry partners</li>
<li>Hold every decision to the standard of our triple bottom line: benefitting the community, providing the best workplace for our employees, and enhancing our guest experience</li>
<li>Grow our business responsibly, by tracking the progress of our efforts and by continuously seeking areas for improvement</li>
<li>And, above all, to maintain transparency in all these efforts</li>
</ul>',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-121645.jpg',
        'uri' => 'public://wallhaven-121645.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 823426,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'c7b43403-97f9-4ad8-bc44-903e3896b202',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1307,
        'uuid_features_file_url' => 'public://wallhaven-121645.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-121501.jpg',
        'uri' => 'public://wallhaven-121501.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 574706,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'a9f988e0-20d7-4b52-8f25-037085d56ce3',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1200,
        'uuid_features_file_url' => 'public://wallhaven-121501.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => 'We understand that sustainability is a journey, and we are involved in the ongoing process of improving our hotel operations and conserving resources. ',
        'format' => NULL,
        'safe_value' => 'We understand that sustainability is a journey, and we are involved in the ongoing process of improving our hotel operations and conserving resources. ',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'As a leader in sustainable hotel accommodations, Easy booking believes that green living is important to the future of our planet.',
        'format' => NULL,
        'safe_value' => 'As a leader in sustainable hotel accommodations, Easy booking believes that green living is important to the future of our planet.',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-01-20 11:15:18 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Our concept',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'dc4ab712-0624-4502-a3b8-d555d2235cfd',
  'type' => 'about',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '12af3948-ae74-4de8-b23d-b291eea21950',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div>
<p>Our attractively decorated apartments offer luxurious amenities with a sleeping area, a separate bathroom, an equipped kitchenette as well as an office space with necessary connections and internet.</p>

<p>Naturally, our residences propose the same services as hotels with, depending on the level, 24/7 reception, daily housekeeping, a leisure area with sauna, Turkish bath, sports room, a business corner, a laundry room, parking, restaurant, etc.Regardless of how long you plan to stay, enjoy hotel services!<br />
&nbsp;<br />
With Easy Booking, you feel right at home!</p>
</div>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Our attractively decorated apartments offer luxurious amenities with a sleeping area, a separate bathroom, an equipped kitchenette as well as an office space with necessary connections and internet.</p>
<p>Naturally, our residences propose the same services as hotels with, depending on the level, 24/7 reception, daily housekeeping, a leisure area with sauna, Turkish bath, sports room, a business corner, a laundry room, parking, restaurant, etc.Regardless of how long you plan to stay, enjoy hotel services!<br />
 <br />
With Easy Booking, you feel right at home!</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-121649.jpg',
        'uri' => 'public://wallhaven-121649.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 784798,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '5db306b3-c2c7-4539-a3a3-8e05a3dc3cb1',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 2400,
        'height' => 1500,
        'uuid_features_file_url' => 'public://wallhaven-121649.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Everywhere in the country, EasyBooking propose four types of apart-hotel, from two to four stars, for business or leisure travel, for a single night, a week or several months.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Everywhere in the country, EasyBooking propose four types of apart-hotel, from two to four stars, for business or leisure travel, for a single night, a week or several months.</p>
',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'hotel-room-2.jpg',
        'uri' => 'public://hotel-room-2_7.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 132029,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '827a4c0d-1b79-4645-954a-20312efae3fd',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1200,
        'height' => 813,
        'uuid_features_file_url' => 'public://hotel-room-2_7.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'jumeirah_beach_hotel.jpg',
        'uri' => 'public://jumeirah_beach_hotel_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 66526,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'f4f71322-d66e-45d7-bdb1-87eefe6fb6a4',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 758,
        'height' => 600,
        'uuid_features_file_url' => 'public://jumeirah_beach_hotel_2.jpg',
      ),
      2 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'guayarmina_princess04.jpg',
        'uri' => 'public://guayarmina_princess04_2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 121684,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '6b0bf94d-c8f1-4a4a-b8d1-4e1cbda981fb',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 800,
        'height' => 801,
        'uuid_features_file_url' => 'public://guayarmina_princess04_2.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => 'Our apart-hotels perfectly meet the needs of a clientele that travels for business, private or vacation purposes.',
        'format' => NULL,
        'safe_value' => 'Our apart-hotels perfectly meet the needs of a clientele that travels for business, private or vacation purposes.',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'Your furnished and equipped apartment with hotel services.',
        'format' => NULL,
        'safe_value' => 'Your furnished and equipped apartment with hotel services.',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Event Spaces',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4ce0dd0c-0826-4a78-bd14-5781c36ae3de',
  'type' => 'about',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4bff4a1c-e5e6-4fa8-b1b2-78d825eab511',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Spanning 10,500 square feet, this classically inspired space blends the Neo-Italian Renaissance stylings of the property’s original architecture with the intricate elegance of the Villard Mansion and an array of modern updates and additions. Detailed molding – rosettes, cornices and ceiling ornaments – has been carefully replicated to evoke the history of The Palace and New York City, while sophisticated window treatments maximize the natural light in each venue.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Spanning 10,500 square feet, this classically inspired space blends the Neo-Italian Renaissance stylings of the property’s original architecture with the intricate elegance of the Villard Mansion and an array of modern updates and additions. Detailed molding – rosettes, cornices and ceiling ornaments – has been carefully replicated to evoke the history of The Palace and New York City, while sophisticated window treatments maximize the natural light in each venue.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-26500.jpg',
        'uri' => 'public://wallhaven-26500_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 734642,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '2dcb2723-2b2c-475a-a7e9-cb8ea6c5fb96',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
        'uuid_features_file_url' => 'public://wallhaven-26500_0.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Spread across four expansive floors, the New York event spaces at The Palace provide a picture-perfect backdrop for events large, small and anywhere in between. Adaptable, flexible and unique, our hotel’s Midtown event spaces can be tailored to suit any event, ranging from stylish soirees to formal business meetings</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Spread across four expansive floors, the New York event spaces at The Palace provide a picture-perfect backdrop for events large, small and anywhere in between. Adaptable, flexible and unique, our hotel’s Midtown event spaces can be tailored to suit any event, ranging from stylish soirees to formal business meetings</p>
',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'hotel-room-2.jpg',
        'uri' => 'public://hotel-room-2_6.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 132029,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '12d44399-8ad1-42e7-8133-83cb42f7a0c3',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1200,
        'height' => 813,
        'uuid_features_file_url' => 'public://hotel-room-2_6.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => '08764746.jpg',
        'uri' => 'public://08764746_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 221891,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '52b5a05d-f146-46fb-8336-133573e99f08',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1500,
        'height' => 1003,
        'uuid_features_file_url' => 'public://08764746_4.jpg',
      ),
      2 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-26500.jpg',
        'uri' => 'public://wallhaven-26500.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 734642,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '6db59610-89ac-4d82-a3a6-1830b4d5e0bd',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1080,
        'uuid_features_file_url' => 'public://wallhaven-26500.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => 'As part of Easy Booking’s rebirth, its fourth- and fifth-floor Midtown meeting venues underwent full redesigns. ',
        'format' => NULL,
        'safe_value' => 'As part of Easy Booking’s rebirth, its fourth- and fifth-floor Midtown meeting venues underwent full redesigns. ',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'Find the perfect venue at Easy Booking',
        'format' => NULL,
        'safe_value' => 'Find the perfect venue at Easy Booking',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  return $nodes;
}
