<?php
/**
 * @file
 * feature_news_nodes.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function feature_news_nodes_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Easy Booking Is the Perfect Place for Paramours',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '9b15f754-e487-4e6f-b9f4-27c8f89416e1',
  'type' => 'news',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '33d4934c-1b67-41d5-a7ab-391bdd7abfbe',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The Palace is conveniently nearby classic landmarks&nbsp;such as Rockefeller Center, The Empire State Building, and Madison Square Garden, which will host the NBA All-Star Game. Central Park is always worth a relaxing stroll in the morning. In the evening, musicals and theater light up Broadway, or just a block away, Saks Fifth Avenue has glittering jewelry for the perfect gift.</p>

<p>Whether this is their first Valentine’s together, or they’ve lost count, our City gives sweethearts the most romantic Valentine’s Day they’ve ever experienced. At Easy booking&nbsp;we’re always dedicated to arranging a luxurious and exquisite holiday. Our Easy Booking Getaway is based on availability and rates do fluctuate depending on stay dates, so reservations&nbsp;should be made promptly.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>The Palace is conveniently nearby classic landmarks such as Rockefeller Center, The Empire State Building, and Madison Square Garden, which will host the NBA All-Star Game. Central Park is always worth a relaxing stroll in the morning. In the evening, musicals and theater light up Broadway, or just a block away, Saks Fifth Avenue has glittering jewelry for the perfect gift.</p>
<p>Whether this is their first Valentine’s together, or they’ve lost count, our City gives sweethearts the most romantic Valentine’s Day they’ve ever experienced. At Easy booking we’re always dedicated to arranging a luxurious and exquisite holiday. Our Easy Booking Getaway is based on availability and rates do fluctuate depending on stay dates, so reservations should be made promptly.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-125785.jpg',
        'uri' => 'public://wallhaven-125785_5.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 486052,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '09bb298e-62a9-4105-8740-238776f452fd',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1200,
        'uuid_features_file_url' => 'public://wallhaven-125785_5.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>On Valentine’s Day, our city becomes the most romantic destination in the world.&nbsp; The city teems with energy and vibrant activity. Manhattan’s majestic skyline takes your breath away and Easy Booking provides luxurious accommodations with an incredible view. In fact, we’ve crafted an enticing luxury hotel package just for valentines. Easy booking&nbsp;treats couples like a King and Queen. For a special night, we’ll provide Valentine’s suites with decadent chocolate-covered strawberries along with a bottle of Louis Roderer champagne to toast the evening. In the morning, In Room Dining provides American breakfast for two. This lavish affair will make lovers feel pampered like royalty.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>On Valentine’s Day, our city becomes the most romantic destination in the world.  The city teems with energy and vibrant activity. Manhattan’s majestic skyline takes your breath away and Easy Booking provides luxurious accommodations with an incredible view. In fact, we’ve crafted an enticing luxury hotel package just for valentines. Easy booking treats couples like a King and Queen. For a special night, we’ll provide Valentine’s suites with decadent chocolate-covered strawberries along with a bottle of Louis Roderer champagne to toast the evening. In the morning, In Room Dining provides American breakfast for two. This lavish affair will make lovers feel pampered like royalty.</p>
',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'wallhaven-121501.jpg',
        'uri' => 'public://wallhaven-121501_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 574706,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'f2a65e07-2565-4198-a1c3-eb95811fced6',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1920,
        'height' => 1200,
        'uuid_features_file_url' => 'public://wallhaven-121501_0.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'Bremen (3 von 13).jpg',
        'uri' => 'public://Bremen (3 von 13).jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 463263,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '4ceeca26-c957-4e36-8997-75fc794ee915',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1600,
        'height' => 1200,
        'uuid_features_file_url' => 'public://Bremen%20%283%20von%2013%29.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => '<p>On Valentine’s, the city is always alive with possibilities.&nbsp;</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>On Valentine’s, the city is always alive with possibilities. </p>
',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'it\'s official',
        'format' => NULL,
        'safe_value' => 'it&#039;s official',
      ),
    ),
  ),
  'field_news_tag' => array(
    'und' => array(
      0 => array(
        'tid' => 2,
        'uuid' => '49e0078e-6962-401a-ae27-72abdd77e428',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'The brunches you have to try',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '78537fcd-7474-4d5a-8254-6f7122253a84',
  'type' => 'news',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '4b5b0bb9-bca9-421e-9ad2-8140d9179e5e',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Glowing diner reviews landed the restaurant inside The Kemper Museum of Contemporary Art on online booking service OpenTable’s list of the country’s top 100 brunch spots, and who are we to argue? Chef Jennifer Maloney’s brunch menu changes weekly but features a few consistent favorites, including the Café Benny, which features poached eggs and Hollandaise sauce served atop meaty crab cakes with a side of roasted potatoes, and the Raisin Brioche French Toast topped with fresh berries and Vermont maple syrup, plus a side of bacon from Missouri-based Burgers’ Smokehouse. The setting—in a colorful courtyard with wall-to-wall art—is as attractive as the dishes.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Glowing diner reviews landed the restaurant inside The Kemper Museum of Contemporary Art on online booking service OpenTable’s list of the country’s top 100 brunch spots, and who are we to argue? Chef Jennifer Maloney’s brunch menu changes weekly but features a few consistent favorites, including the Café Benny, which features poached eggs and Hollandaise sauce served atop meaty crab cakes with a side of roasted potatoes, and the Raisin Brioche French Toast topped with fresh berries and Vermont maple syrup, plus a side of bacon from Missouri-based Burgers’ Smokehouse. The setting—in a colorful courtyard with wall-to-wall art—is as attractive as the dishes.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => '08764746.jpg',
        'uri' => 'public://08764746_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 221891,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'ae1ffcbc-07b6-4ec4-ad97-b252f71c36fc',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1500,
        'height' => 1003,
        'uuid_features_file_url' => 'public://08764746_1.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Consider the facts: You’re allowed to start drinking before noon, the food is comforting and delicious and it’s the perfect opportunity to unwind before jumping into the busy week ahead. We rounded up a dozen morning meals worth getting out of bed for from all over KC.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Consider the facts: You’re allowed to start drinking before noon, the food is comforting and delicious and it’s the perfect opportunity to unwind before jumping into the busy week ahead. We rounded up a dozen morning meals worth getting out of bed for from all over KC.</p>
',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'image_1.jpg',
        'uri' => 'public://image_1_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 149020,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '73c5e30f-a9b2-4c1f-98d6-6bd91b39c8bf',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1024,
        'height' => 768,
        'uuid_features_file_url' => 'public://image_1_1.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'guayarmina_princess04.jpg',
        'uri' => 'public://guayarmina_princess04_4.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 121684,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '54c39b42-d9b6-4a05-8159-d799fb793ef8',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 800,
        'height' => 801,
        'uuid_features_file_url' => 'public://guayarmina_princess04_4.jpg',
      ),
      2 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'rimonim-eilat-hotel.jpg',
        'uri' => 'public://rimonim-eilat-hotel_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 53124,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '8f68632d-7eae-4553-8407-041b5164f61e',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 620,
        'height' => 350,
        'uuid_features_file_url' => 'public://rimonim-eilat-hotel_0.jpg',
      ),
      3 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'hotel-room-2.jpg',
        'uri' => 'public://hotel-room-2_8.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 132029,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '43fa1817-ba4e-4287-bdce-b143c7a81a89',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1200,
        'height' => 813,
        'uuid_features_file_url' => 'public://hotel-room-2_8.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Yes, this Crossroads-based restaurant specializes in the cuisine of its owners’ native Germany, but Affäre’s Sunday-only brunch menu proves there’s more to Continental breakfast than cold cuts and cheese plates. Choose from familiar favorites with a European spin, including Arme Ritter, the German version of French toast, made with brioche bread and topped with vanilla sauce; Kaiserschmarrn, shredded, fluffy crepes served with almonds, rum raisins and caramelized apples; and the Affäre Omelette, stuffed with house-cured Canadian style ham, red peppers, asparagus, and fontina cheese. Or try something new—like our favorite, the Käsespätzle, soft egg noodles topped with a blend of cheeses, plus chorizo and onions. Wash it all down with a Bloody Mary with your choice of add-ons, such as bacon powder, blue cheese or a shrimp skewer, or opt for endless mimosas for $10.</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Yes, this Crossroads-based restaurant specializes in the cuisine of its owners’ native Germany, but Affäre’s Sunday-only brunch menu proves there’s more to Continental breakfast than cold cuts and cheese plates. Choose from familiar favorites with a European spin, including Arme Ritter, the German version of French toast, made with brioche bread and topped with vanilla sauce; Kaiserschmarrn, shredded, fluffy crepes served with almonds, rum raisins and caramelized apples; and the Affäre Omelette, stuffed with house-cured Canadian style ham, red peppers, asparagus, and fontina cheese. Or try something new—like our favorite, the Käsespätzle, soft egg noodles topped with a blend of cheeses, plus chorizo and onions. Wash it all down with a Bloody Mary with your choice of add-ons, such as bacon powder, blue cheese or a shrimp skewer, or opt for endless mimosas for $10.</p>
',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'Food and drink',
        'format' => NULL,
        'safe_value' => 'Food and drink',
      ),
    ),
  ),
  'field_news_tag' => array(
    'und' => array(
      0 => array(
        'tid' => 2,
        'uuid' => '49e0078e-6962-401a-ae27-72abdd77e428',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  $nodes[] = array(
  'uid' => 0,
  'title' => 'Easy booking moves to the new place',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '1a49bcdd-3a5b-4895-b651-9cecd97c1fb8',
  'type' => 'news',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '847d8bb4-d9d1-443d-a773-44727854189e',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Slated to open in January, the 123-room Easy Booking is only the second of its kind to open in the United States. (A New Orleans location opened in the fall.) The sleek, modern look of the Easy Booking&nbsp;brand reflects the aesthetics of the European countries where it was first introduced and pairs high style with high tech, offering mobile check-in and USB charging stations. The hotel’s&nbsp;Lounge, which will serve drinks and a tapas-style menu, will<br />
accommodate visitors as well as guests.</p>
',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Slated to open in January, the 123-room Easy Booking is only the second of its kind to open in the United States. (A New Orleans location opened in the fall.) The sleek, modern look of the Easy Booking brand reflects the aesthetics of the European countries where it was first introduced and pairs high style with high tech, offering mobile check-in and USB charging stations. The hotel’s Lounge, which will serve drinks and a tapas-style menu, will<br />
accommodate visitors as well as guests.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_news_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'guayarmina_princess04.jpg',
        'uri' => 'public://guayarmina_princess04_3.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 121684,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '40073d9c-8ab7-434e-ad52-14ce4aa43e3d',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 800,
        'height' => 801,
        'uuid_features_file_url' => 'public://guayarmina_princess04_3.jpg',
      ),
    ),
  ),
  'field_news_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<div>
<p>With the opening of several sophisticated new dining spots in Westport, such as Easy Booking, it seems only fitting that the area have an upscale new hotel to accommodate out-of-town visitors.</p>
</div>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>With the opening of several sophisticated new dining spots in Westport, such as Easy Booking, it seems only fitting that the area have an upscale new hotel to accommodate out-of-town visitors.</p>
',
      ),
    ),
  ),
  'field_news_slideshow' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'image_1.jpg',
        'uri' => 'public://image_1_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 149020,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '7cc0a213-191a-4cd2-ac63-03d9fa2066e9',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1024,
        'height' => 768,
        'uuid_features_file_url' => 'public://image_1_0.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'eser-premium-hotel-spa.jpg',
        'uri' => 'public://eser-premium-hotel-spa_1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 45905,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '894328f0-d04f-41fb-8a4b-35d729ae3cbc',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 550,
        'height' => 365,
        'uuid_features_file_url' => 'public://eser-premium-hotel-spa_1.jpg',
      ),
      2 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'hotel-room-2.jpg',
        'uri' => 'public://hotel-room-2.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 132029,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '2b53bd3d-4e21-4beb-bd20-b865b02cbf31',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1200,
        'height' => 813,
        'uuid_features_file_url' => 'public://hotel-room-2.jpg',
      ),
    ),
  ),
  'field_news_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Those traveling to KC will soon have a stylish new hotel to consider.&nbsp;</p>
',
        'format' => 'filtered_html',
        'safe_value' => '<p>Those traveling to KC will soon have a stylish new hotel to consider. </p>
',
      ),
    ),
  ),
  'field_news_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'Travel / adventure',
        'format' => NULL,
        'safe_value' => 'Travel / adventure',
      ),
    ),
  ),
  'field_news_tag' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
        'uuid' => 'db56ead8-51a5-474e-a925-8110c877e2ca',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  return $nodes;
}
