<?php
/**
 * @file
 * feature_our_hotel_node.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function feature_our_hotel_node_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 0,
  'title' => 'Our hotel',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '51c4d3b2-6b52-4f9e-bcfc-541c331bfdae',
  'type' => 'article',
  'language' => 'und',
  'created' => 1423474912,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd2ae085a-a575-415f-b44f-2e9832b7046a',
  'revision_uid' => 1,
  'body' => array(),
  'field_body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Easy Boking offers the following amenities:</p><ul><li>Deluxe non-smoking guestrooms with Simmons Beautyrest&reg; pillow top mattresses</li><li>Buffet-style dining where kids eat free (under 10 years of age with paying adult)</li><li>Restaurants on property</li><li>Free Wi-Fi in guestrooms and public places</li><li>24-hour security team and free, gated parking</li><li>Fully accessible ADA rooms available</li><li>Two seasonally heated swimming pools, video arcade game room, playground</li><li>Business center</li><li>No resort fees</li></ul>',
        'format' => 'full_html',
        'safe_value' => '<p>Easy Boking offers the following amenities:</p>
<ul><li>Deluxe non-smoking guestrooms with Simmons Beautyrest® pillow top mattresses</li>
<li>Buffet-style dining where kids eat free (under 10 years of age with paying adult)</li>
<li>Restaurants on property</li>
<li>Free Wi-Fi in guestrooms and public places</li>
<li>24-hour security team and free, gated parking</li>
<li>Fully accessible ADA rooms available</li>
<li>Two seasonally heated swimming pools, video arcade game room, playground</li>
<li>Business center</li>
<li>No resort fees</li>
</ul>',
      ),
    ),
  ),
  'field_image' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'guayarmina_princesss04.jpg',
        'uri' => 'public://guayarmina_princesss04.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 121684,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '65d174ea-b0f8-483b-9db9-805efe577cc1',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 800,
        'height' => 801,
        'uuid_features_file_url' => 'public://guayarmina_princesss04.jpg',
      ),
    ),
  ),
  'field_outline' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Easy booking is located in the heart of International Drive within walking distance of restaurants, entertainment, malls and&nbsp;monuments. The hotel features 1,020 specious rooms within six high-rise buildings. Easy Booking provides families planning to explore theme parks and professionals visiting for business a comfortable hotel to enjoy. Because of Easy Booking&rsquo;s prime position across the street, Easy Booking has a plethora of restaurants, bars and other entertainment options that are easily accessible</p>',
        'format' => 'full_html',
        'safe_value' => '<p>Easy booking is located in the heart of International Drive within walking distance of restaurants, entertainment, malls and monuments. The hotel features 1,020 specious rooms within six high-rise buildings. Easy Booking provides families planning to explore theme parks and professionals visiting for business a comfortable hotel to enjoy. Because of Easy Booking’s prime position across the street, Easy Booking has a plethora of restaurants, bars and other entertainment options that are easily accessible</p>
',
      ),
    ),
  ),
  'field_slideshow_comment' => array(
    'und' => array(
      0 => array(
        'value' => '<p><span style="line-height: 20.7999992370605px;">Easy booking</span><span style="line-height: 20.7999992370605px;">&nbsp;sets the standard for the&nbsp;</span><span style="line-height: 20.7999992370605px;">Easy booking&nbsp;</span><span style="line-height: 20.7999992370605px;">hotel family. Over the years,&nbsp;</span><span style="line-height: 20.7999992370605px;">Easy booking</span><span style="line-height: 20.7999992370605px;">&nbsp;has been presented with several awards that solidify our customer&rsquo;s satisfaction.</span></p>',
        'format' => 'full_html',
        'safe_value' => '<p><span style="line-height: 20.7999992370605px;">Easy booking</span><span style="line-height: 20.7999992370605px;"> sets the standard for the </span><span style="line-height: 20.7999992370605px;">Easy booking </span><span style="line-height: 20.7999992370605px;">hotel family. Over the years, </span><span style="line-height: 20.7999992370605px;">Easy booking</span><span style="line-height: 20.7999992370605px;"> has been presented with several awards that solidify our customer’s satisfaction.</span></p>
',
      ),
    ),
  ),
  'field_slideshow_images' => array(
    'und' => array(
      0 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => '08764746.jpg',
        'uri' => 'public://08764746_0.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 221891,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'd9c4acae-79b5-4dd9-b5f8-8b890c5e504b',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 1500,
        'height' => 1003,
        'uuid_features_file_url' => 'public://08764746_0.jpg',
      ),
      1 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'eser-premium-hotel-spa.jpg',
        'uri' => 'public://eser-premium-hotel-spa.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 45905,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'a11370f0-1f26-4dde-8a6a-2e00a6bb2e1c',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 550,
        'height' => 365,
        'uuid_features_file_url' => 'public://eser-premium-hotel-spa.jpg',
      ),
      2 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'rimonim-eilat-hotel.jpg',
        'uri' => 'public://rimonim-eilat-hotel.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 53124,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => '3d2ddd72-1ea7-4eea-9662-55993e217358',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 620,
        'height' => 350,
        'uuid_features_file_url' => 'public://rimonim-eilat-hotel.jpg',
      ),
      3 => array(
        'fid' => NULL,
        'uid' => 1,
        'filename' => 'MARINA_ROYAL_PALACE1.jpg',
        'uri' => 'public://MARINA_ROYAL_PALACE1.jpg',
        'filemime' => 'image/jpeg',
        'filesize' => 56395,
        'status' => 1,
        'timestamp' => NULL,
        'uuid' => 'ab3156ec-efcd-4024-ac90-898101bc7217',
        'rdf_mapping' => array(),
        'alt' => '',
        'title' => '',
        'width' => 675,
        'height' => 506,
        'uuid_features_file_url' => 'public://MARINA_ROYAL_PALACE1.jpg',
      ),
    ),
  ),
  'field_subtitle' => array(
    'und' => array(
      0 => array(
        'value' => 'We focus on remarkable service, first-rate accommodations, and great value.',
        'format' => NULL,
        'safe_value' => 'We focus on remarkable service, first-rate accommodations, and great value.',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => '',
  'picture' => 0,
  'data' => NULL,
  'date' => '2015-02-09 15:41:52 +0600',
);
  return $nodes;
}
