<?php

function edville_custom_form_rooms_booking_availability_search_form_block_alter(&$form, &$form_state, $form_id) {
  $form['rooms_date_range']['rooms_start_date']['#attributes']['placeholder'] = $form['rooms_date_range']['rooms_start_date']['#title'];
  unset($form['rooms_date_range']['rooms_start_date']['#title']);

  $form['rooms_date_range']['rooms_end_date']['#attributes']['placeholder'] = $form['rooms_date_range']['rooms_end_date']['#title'];
  unset($form['rooms_date_range']['rooms_end_date']['#title']);


  $form['conditions']['rooms']['#options'] = array(
    -1 => $form['conditions']['rooms']['#title']
    ) + $form['conditions']['rooms']['#options'];
  $form['conditions']['rooms']['#default_value'] = -1;
  unset($form['conditions']['rooms']['#title']);
  $form['conditions']['#weight'] = 99;


  $form['rooms_fieldset']['group_size_adults:1']['#options'] = array(
    -1 => $form['rooms_fieldset']['group_size_adults:1']['#title']
    ) + $form['rooms_fieldset']['group_size_adults:1']['#options'];
  $form['rooms_fieldset']['group_size_adults:1']['#default_value'] = -1;
  unset($form['rooms_fieldset']['group_size_adults:1']['#title']);

  $form['rooms_fieldset']['group_size_children:1']['#options'] = array(
    -1 => $form['rooms_fieldset']['group_size_children:1']['#title']
    ) + $form['rooms_fieldset']['group_size_children:1']['#options'];
  $form['rooms_fieldset']['group_size_children:1']['#default_value'] = -1;
  unset($form['rooms_fieldset']['group_size_children:1']['#title']);
  
  $form['actions']['submit']['#value'] = t('Search');

  $form['#validate'][] = 'edville_custom_room_search_validate';
  $form['conditions']['rooms']['#default_value'] = 1;
  $form['conditions']['rooms']['#attributes']['class'] = array('hide');
  
}

function edville_custom_room_search_validate($form, &$form_state) {

  if ($form_state['values']['rooms'] == -1) {
    form_set_error('rooms');
  }
  if ($form_state['values']['group_size_adults:1'] == -1) {
    form_set_error('group_size_adults:1');
  }
  if ($form_state['values']['group_size_children:1'] == -1) {
    form_set_error('group_size_children:1');
  }
}

function edville_custom_form_rooms_booking_manager_change_search_form_alter(&$form, &$form_state, $form_id) {
  
  $booking_parameters = reset(unserialize($form['info']['params']['booking_parameters']['#value']));
  
  if (isset($booking_parameters['adults']) && isset($form['info']['units'])) {
    $form['info']['units']['#markup'] = '<label>People</label> <span class="info">' . $booking_parameters['adults'] . '</span>';
  }

}

function edville_custom_form_rooms_booking_availability_search_form_page_alter(&$form, &$form_state, $form_id) {
  $form['rooms_date_range']['rooms_start_date']['#attributes']['placeholder'] = $form['rooms_date_range']['rooms_start_date']['#title'];
  unset($form['rooms_date_range']['rooms_start_date']['#title']);

  $form['rooms_date_range']['rooms_end_date']['#attributes']['placeholder'] = $form['rooms_date_range']['rooms_end_date']['#title'];
  unset($form['rooms_date_range']['rooms_end_date']['#title']);


  $form['conditions']['rooms']['#options'] = array(
    -1 => $form['conditions']['rooms']['#title']
    ) + $form['conditions']['rooms']['#options'];
  unset($form['conditions']['rooms']['#title']);
  $form['conditions']['#weight'] = 99;

  $form['rooms_fieldset']['group_size_adults:1']['#options'] = array(
    -1 => $form['rooms_fieldset']['group_size_adults:1']['#title']
    ) + $form['rooms_fieldset']['group_size_adults:1']['#options'];
  unset($form['rooms_fieldset']['group_size_adults:1']['#title']);
  if (!isset($_GET['rooms_group_size1'])) {
    $form['rooms_fieldset']['group_size_adults:1']['#default_value'] = -1;
  }

  $form['rooms_fieldset']['group_size_children:1']['#options'] = array(
    -1 => $form['rooms_fieldset']['group_size_children:1']['#title']
    ) + $form['rooms_fieldset']['group_size_children:1']['#options'];
  unset($form['rooms_fieldset']['group_size_children:1']['#title']);
  if (!isset($_GET['rooms_children1'])) {
    $form['rooms_fieldset']['group_size_children:1']['#default_value'] = -1;
  }
  
  $form['actions']['submit']['#value'] = t('Search');

  $form['#validate'][] = 'edville_custom_room_search_validate';
  $form['conditions']['rooms']['#default_value'] = 1;
  $form['conditions']['rooms']['#attributes']['class'] = array('hide');
  drupal_add_js("jQuery(document).ready(function() {
    jQuery('#edit-rooms').closest('.form-type-select').hide();
  })", 'inline');
}